# Generated by Django 3.1.4 on 2021-02-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=4)),
                ('detail', models.TextField()),
                ('image', models.CharField(max_length=2033)),
            ],
        ),
    ]
