# Generated by Django 3.1.4 on 2021-02-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_salads_starters'),
    ]

    operations = [
        migrations.CreateModel(
            name='chefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Photos')),
                ('twitter', models.URLField(max_length=3000)),
                ('facebook', models.URLField(max_length=3000)),
                ('instagram', models.URLField(max_length=3000)),
                ('linkedin', models.URLField(max_length=3000)),
            ],
        ),
    ]
